# GET http://localhost:3000?tenant=develop
# Content-Type: application/json

# {
#     "tenant":"develop"
# }

###$

get http://localhost:3000/post/random-image  HTTP/1.1
Content-Type: application/json

{
    "name":"Vlad",
    "age":23
}


